/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dvulist.simplexmethod;

import com.dvulist.simplexmethod.customui.PanelForConstrain;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {

    
    public MainForm() {
        initComponents();
        
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        reloadPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerWithoutArrows1 = new com.dvulist.simplexmethod.customui.SpinnerWithoutArrows();
        spinnerWithoutArrows2 = new com.dvulist.simplexmethod.customui.SpinnerWithoutArrows();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1000));
        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 1));
        jScrollPane2.setViewportView(jPanel2);

        jLabel1.setText("Количество переменных");

        jLabel2.setText("Количество ограничений");

        jLabel3.setText("Целевая функция");

        spinnerWithoutArrows1.setModel(new javax.swing.SpinnerNumberModel(3, 1, 1000, 1));
        spinnerWithoutArrows1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerWithoutArrows1StateChanged(evt);
            }
        });

        spinnerWithoutArrows2.setModel(new javax.swing.SpinnerNumberModel(3, 1, 1000, 1));
        spinnerWithoutArrows2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerWithoutArrows2StateChanged(evt);
            }
        });

        jLabel4.setText("Ограничения");

        jButton1.setText("Решить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(spinnerWithoutArrows2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spinnerWithoutArrows1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 373, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinnerWithoutArrows1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerWithoutArrows2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");
        jLabel2.getAccessibleContext().setAccessibleName("jLabel2");
        jLabel3.getAccessibleContext().setAccessibleName("jLabel3");
        jLabel3.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MyData data = new MyData(jPanel1, jPanel2);
        
        for (ArrayList<Double> row : data.rows) {
            for (double i : row) {
                System.out.print(i + " ");
            }
            System.out.println();
        }
        for (Double i : data.targetFunctionVars) {
                System.out.print(i + " ");
        }
        System.out.println();
        
        data.SimplexMaximizationMethod();
        System.out.println();
        
        for (ArrayList<Double> row : data.rows) {
            for (Double i : row) {
                System.out.print(i + " ");
            }
            System.out.println();
        }
        for (Double i : data.targetFunctionVars) {
                System.out.print(i + " ");
        }
        System.out.println();
        
        data.SimplexMaximizationMethod();
        System.out.println();
        
        for (ArrayList<Double> row : data.rows) {
            for (Double i : row) {
                System.out.print(i + " ");
            }
            System.out.println();
        }
        for (Double i : data.targetFunctionVars) {
                System.out.print(i + " ");
        }
        
        for (int i : data.X) {
            System.out.println(i);
        }
        
        data.SimplexMaximizationMethod();
        System.out.println();
        
        for (ArrayList<Double> row : data.rows) {
            for (Double i : row) {
                System.out.print(i + " ");
            }
            System.out.println();
        }
        for (Double i : data.targetFunctionVars) {
                System.out.print(i + " ");
        }
        
        for (int i : data.X) {
            System.out.println(i);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void reloadPanels() {
        jPanel1.removeAll();
        jPanel1.add(new PanelForConstrain(Integer.parseInt(spinnerWithoutArrows1.getValue().toString()), false));
        
        jPanel2.removeAll();
        
        int numOfVar = Integer.parseInt(spinnerWithoutArrows1.getValue().toString());
        int constrainsLen = Integer.parseInt(spinnerWithoutArrows2.getValue().toString());
        
        for (int i=0; i < constrainsLen; i++) {
            jPanel2.add(new PanelForConstrain(numOfVar, true));
        }
        
        jPanel1.revalidate();
        jPanel1.repaint();
        
        jPanel2.revalidate();
        jPanel2.repaint();
    }
    
    private void spinnerWithoutArrows1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerWithoutArrows1StateChanged
        reloadPanels();
    }//GEN-LAST:event_spinnerWithoutArrows1StateChanged

    private void spinnerWithoutArrows2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerWithoutArrows2StateChanged
        reloadPanels();
    }//GEN-LAST:event_spinnerWithoutArrows2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.dvulist.simplexmethod.customui.SpinnerWithoutArrows spinnerWithoutArrows1;
    private com.dvulist.simplexmethod.customui.SpinnerWithoutArrows spinnerWithoutArrows2;
    // End of variables declaration//GEN-END:variables
}
